extra_css:
- assets/versions.css
extra_javascript:
- assets/versions.js

site_name: OpsMx ISD Documentation
theme:
  name: material
  logo: logo.svg
  palette:
    primary: cyan
    accent: cyan
  icon:  
    admonition:
      note: material/alert-circle-outline

nav:
    - Home: index.md
    - Overview:
       - OpsMx Intelligent Software Delivery Platform.md
       - Overview: Overview.md
       - Orchestration Module - OpsMx Enterprise for Spinnaker (OES).md
       - OES Features.md
       - Automated Workflows.md
       - Multi-cloud Deployments.md
       - Safe-Deployment strategies.md
       - Scalable & Extensible.md
       - OES Concepts.md
       - Application Management.md
       - Application Deployment.md
       - Data and Intelligence Module - Autopilot.md
       - Observability.md
       - Audit and Traceability.md
       - Continuous Compliance - Policy.md
    - Getting Started:
       - ISD Quick Installation.md
       - Trial User Guide.md
       - SaaS Trial Usage Instruction Video.md
    - Operator Manual:
       - ISD Architecture.md
       - ISD Deployment Architecture.md
       - Environment setup for OpsMx ISD.md
       - ISD On-Prem POV Infrastructure requirements.md
       - Installation.md
       - ISD Installation Guide.md
       - ISD GitOps Installation.md
       - ISD Installation Configuration.md
       - Helm Chart based installation.md
       - ISD Installation on OpenShift.md

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ops_mx
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/OpsMxInc/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/opsmx/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCFIqwYzo-2LGShQCVFy9LWg

  analytics:
    provider: google
    property: G-XXXXXXXXXX

    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

  version:
    provider: mike

  generator: false

  
copyright: "&copy; 2022 All Rights Reserved <script>document.write</script>"

plugins:
  - search
  - autolinks
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

repo_url: https://github.com/Somasekhar-nakkala/Somasekhar-nakkala.github.io

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences