extra_css:
  - stylesheets/extra.css

site_name: OpsMx ISD Documentation
theme:
  name: material
  highlightjs: false
  logo: logo.svg
  palette:
    primary: cyan
    accent: cyan
  icon:  
    admonition:
      note: material/alert-circle-outline

nav:
    - Home: index.md
    - Overview:
       - OpsMx Intelligent Software Delivery Platform.md
       - Overview: Overview.md
       - Orchestration Module - OpsMx Enterprise for Spinnaker (OES).md
       - OES Features.md
       - Automated Workflows.md
       - Multi-cloud Deployments.md
       - Safe-Deployment strategies.md
       - Scalable & Extensible.md
       - OES Concepts.md
       - Application Management.md
       - Application Deployment.md
       - Data and Intelligence Module - Autopilot.md
       - Observability.md
       - Audit and Traceability.md
       - Continuous Compliance - Policy.md
    - Getting Started:
       - ISD Quick Installation.md
       - Trial User Guide.md
       - SaaS Trial Usage Instruction Video.md
    - Operator Manual:
       - ISD Architecture.md
       - ISD Deployment Architecture.md
       - Environment setup for OpsMx ISD.md
       - ISD On-Prem POV Infrastructure requirements.md
       - Installation.md
       - ISD Installation Guide.md
       - ISD GitOps Installation.md
       - ISD Installation Configuration.md
       - Helm Chart based installation.md
       - ISD Installation on OpenShift.md
       - Autopilot Installation.md
       - Routing Web URLs to ISD services.md
       - ISD Service Catalogue.md
       - ISD - Commonly used Commands.md
       - Promethues and Kubernetes.md
    - User Guide:
       - Application Dashboard.md
       - Application Service View.md
       - Manage Application.md
       - Create an Application.md
       - Configure an Application.md
       - Delete an Application.md
       - Create a Pipeline.md
       - Add Stage.md
       - Add Trigger.md
       - Edit Pipeline.md
       - Rename Pipeline.md
       - Delete Pipeline.md
       - Disable Pipeline.md
       - Lock Pipeline.md
       - View and Restore Pipeline.md
       - Approval Gate.md
       - Add Verification Gate.md
       - Add Test Verification Gate.md
       - Add Policy Gate.md
       - Deployment to Kubernetes namespace with Manifest file.md
       - Deployment to Kubernetes namespace with Git based Manifest.md
       - Manual Approval before deployment.md
       - Blue-Green deployment using Manifest.md
       - Helm based deployment to Kubernetes namespace.md
       - Integrations.md
       - Available Integrations.md

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ops_mx
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/OpsMxInc/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/opsmx/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCFIqwYzo-2LGShQCVFy9LWg

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  analytics:
    provider: google
    property: UA-240811344-1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://docs.google.com/forms/d/e/1FAIpQLSeW6eQR8xwAXddhnrIgLwToHyV305wHLaTtmP1zxygXYYmx7A/viewform?vc=0&c=0&w=1&flr=0" target="_blank" rel="noopener">Customer Feedback</a>.


  version:
    provider: mike

  generator: false

  
copyright: "&copy; 2022 All Rights Reserved <script>document.write</script>"

plugins:
  - search
  - autolinks
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

repo_name: Somasekhar-nakkala/Somasekhar-nakkala.github.io
repo_url: https://github.com/Somasekhar-nakkala/Somasekhar-nakkala.github.io

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html

  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
